version: '3.6'

services:

  mongo:
    image: mongo
    ports:
      - 8081:8081
    networks:
      - ebk-compose_elk

  rabbitmq:
    image: rabbitmq:management
    ports:
      - 15672:15672
    networks:
      - ebk-compose_elk

  haproxy:
    build: ./haproxy
    ports:
      - 9000:9000
    networks:
      - ebk-compose_elk

  apache:
    build: ./apache
    ports:
      - 8080:80
    networks:
      - ebk-compose_elk

  web:
    build: .
    volumes:
      - ./:/app
    working_dir: /app
    command: puma
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres@db
    networks:
      - ebk-compose_elk

  db:
    image: postgres:10.3-alpine
    volumes:
      - ./dbconf/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
        #      - ./dblog:/var/lib/postgresql/data/dblog
    environment:
      - PGDATA=/tmp
    networks:
      - ebk-compose_elk

networks:
  ebk-compose_elk:
    external: true
